# Sample configuration file for route optimization platform.
# This file is used by config_loader.py to set up environment-specific settings.

aws_region: "us-east-1"
vpc_cidr: "10.0.0.0/16"
public_subnet_cidrs:
  - "10.0.1.0/24"
  - "10.0.2.0/24"
availability_zones:
  - "us-east-1a"
  - "us-east-1b"
ami_id: "ami-0abcdef1234567890"  # Replace with a valid AMI ID.
instance_type: "t3.medium"
key_pair: "my-key-pair"
